version: '3'
services:
  simplehttpserver:
    image: salvq/simplehttpserver:1.2.0
    container_name: simplehttpserver
    restart: unless-stopped
    ports:
      - "8019:8000"
    volumes:
      - /share/Container/simplehttpserver:/simplehttpserver
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://192.168.1.106:514"
        tag: "{{.Name}}/{{.ImageName}}"
    networks:
      others:
         ipv4_address: 172.18.15.144
networks:
  others:
    external: true