version: '3'
services:
  simplehttpserver:
    image: salvq/simplehttpserver:1.2.0
    container_name: simplehttpserver
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - /share/Container/simplehttpserver:/simplehttpserver
    networks:
      others:
         ipv4_address: 172.18.5.44
networks:
  others:
    external: true
